import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { ArtProvider } from "@/components/useArtContext";
import { Analytics } from "@vercel/analytics/react"


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ArtProvider>
            <Header />
            {children}
            <Footer />
          </ArtProvider>
          <Analytics />
      </body>
    </html>
  );
}
